artifact_location: C:\Users\Deepanshu\Downloads\sentiment-api\mlruns2
creation_time: 1756464650786
experiment_id: '544646876329249287'
last_update_time: 1756464650786
lifecycle_stage: active
name: sentiment-api
