name: CI - Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Install dependencies from sentiment-api folder
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r sentiment-api/requirements.txt

    # 4️⃣ Run tests inside sentiment-api folder
    - name: Run tests
      run: |
        pytest sentiment-api --maxfail=1 --disable-warnings -q
