name: CD - Deploy to Render

on:
  push:
    branches: [ main ]  # triggers on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Deploy to Render
      - name: Deploy to Render
        uses: render-examples/deploy-action@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: srv-d2onividbo4c73bqq4cg  # your service ID from Render

      # 3️⃣ Confirmation
      - name: Deployment complete
        run: echo "Render deployment triggered successfully!"